### ISSUE TITLE
Implementar view da janela para criação de elementos.

### ISSUE THREAD

**Issue by GNakayama** [GNakayama/INE5420#1]
Criar janela de acordo com o figura nos slides, para que possa ser criadas elementos do tipo ponto, linha e poligono no viewport.

**Comment by caian-gums** [comment]
Implementado com a janela de criação de: Ponto, Linha e Círculo. Para Polígonos ainda precisa ver como vai ser feito.
A Janela está abrindo junto ao início do programa. Talvez disparar por um Evento ou até integrar a janela a interface.

**Comment by caian-gums** [comment]
Aba de Poligonos adicionada e janela melhor 'enquadrada'.
