### ISSUE TITLE
Implementar a estrutura de dado Lista Encadeada

### ISSUE THREAD

**Issue by GNakayama** [GNakayama/INE5420#3]
Implementar a estrutura de dados lista encadeada baseando-se na classe ListaEnc fornecida pelo professor.

**Comment by caian-gums** [comment]
Vou implementar.

**Comment by caian-gums** [comment]
Lista parcialmente implementada. Tem que verificar se está sendo liberada a memória de maneira correta nas funções de retirada de dados.

**Comment by caian-gums** [comment]
Lista implementada. Apenas funções booleanas não foram feitas.
Ainda precisa revisar funções que destroem(seria como dar free em C) pois não sei se estão corretas.
